version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-dew_auth}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dew_auth_password}
      - POSTGRES_DB=${POSTGRES_DB:-dew_auth_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dew_auth}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  dew-auth-server:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8050:8050
    environment:
      - DEW_AUTH_DATABASE_URL=postgres://${POSTGRES_USER:-dew_auth}:${POSTGRES_PASSWORD:-dew_auth_password}@db:5432/${POSTGRES_DB:-dew_auth_db}?sslmode=disable
      - DEW_AUTH_REDIS_ADDRESS=redis:6379
      - DEW_AUTH_SERVER_HOST=0.0.0.0
      - DEW_AUTH_SERVER_PORT=8050
      - DEW_AUTH_SERVER_TLS_CERT_PATH=./certs/cert.pem
      - DEW_AUTH_SERVER_TLS_KEY_PATH=./certs/key.pem
      - DEW_AUTH_SERVER_TEMPLATE_PATH=./server/controllers/templates
      - DEW_AUTH_SESSION_SIGNING_KEY=${SESSION_SIGNING_KEY:-0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF}
      - DEW_AUTH_SESSION_ENCRYPTION_KEY=${SESSION_ENCRYPTION_KEY:-FEDCBA9876543210FEDCBA9876543210FEDCBA9876543210FEDCBA9876543210}
      - DEW_AUTH_OAUTH_AUTH_CODE_LIFETIME=600s
      - DEW_AUTH_OAUTH_ACCESS_TOKEN_LIFETIME=3600s
      - DEW_AUTH_OAUTH_REFRESH_TOKEN_LIFETIME=2592000s
      - DEW_AUTH_LOGGING_LEVEL=info
      - DEW_AUTH_CORS_ALLOW_ORIGINS=*
      - DEW_AUTH_RATE_LIMIT_ENABLED=true
    volumes:
      - ./certs:/app/certs

volumes:
  postgres_data:
  redis_data: