name: Make Scripts Executable

on:
  push:
    paths:
      - 'scripts/**'

jobs:
  make-executable:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Make scripts executable"
          file_pattern: scripts/*.sh